name: arc_player
description: "A clean and modern music player app"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  
  # State Management and Routing
  get: ^4.6.6
  
  # Local Database for Settings
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Audio Playback
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.17
  audio_session: ^0.1.18
  
  # Fetching Local Files and Permissions
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
